# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UniQuiziOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for UniQuiziOS

  target 'UniQuiziOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UniQuiziOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end


	
end
